name: Docker Image CI

on: 
  push:
    branches:
    - master
  check_run:
    types: [rerequested, requested_action]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag englishlearning-multimedia:$(date +%s)
